# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do | config |
	# Common configuration for the VM
	config.vm.box = "ubuntu/focal64"

	# Configuration globale pour VirtualBox
	config.vm.provider "virtualbox" do |vb|
	  vb.memory = 2048
	  vb.cpus = 2
	end

	# === Serveur K3s ===
	config.vm.define "tde-los-S" do | server |
		server.vm.hostname = "tde-los-S"
		server.vm.network "private_network", ip: "192.168.56.110"

	  	# Provisioning
		server.vm.provision "shell", path: "scripts/install_k3s.sh"
		# server.vm.provision "shell", path: "scripts/deploy_apps.sh"
	end
  end
