# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Common configuration for all VMs
  config.vm.box = "bento/ubuntu-22.04-arm64"
  
  # Server VM
  config.vm.define "acoezardS" do |server|
    server.vm.hostname = "acoezardS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # VM resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    
    # Provisioning
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
    
    # Forward SSH key for authentication
    server.ssh.forward_agent = true
  end
  
  # Worker VM
  config.vm.define "acoezardSW" do |worker|
    worker.vm.hostname = "acoezardSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    # VM resources
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    
    # Provisioning
    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
    
    # Forward SSH key for authentication
    worker.ssh.forward_agent = true
  end
end 