# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Common configuration for all VMs
  config.vm.box = "roboxes/ubuntu2204"

  config.vm.boot_timeout = 600 # Boot timeout to 10 minutes
  
  # Basic SSH settings
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Server VM
  config.vm.define "acoezardS" do |server|
    server.vm.hostname = "acoezardS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # VirtualBox config - for running inside UTM VM
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024  # 1024MB as recommended in the subject
      vb.cpus = 1       # 1 CPU as recommended in the subject
      vb.name = "acoezardS"
    end
    
    # Provisioning
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end
  
  # Worker VM
  config.vm.define "acoezardSW" do |worker|
    worker.vm.hostname = "acoezardSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    # VirtualBox config - for running inside UTM VM
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024  # Use 1024MB as recommended in the subject
      vb.cpus = 1       # Use 1 CPU as recommended in the subject
      vb.name = "acoezardSW"
    end
    
    # Provisioning
    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end
end 