# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/focal64"
  config.vm.box = "generic/ubuntu2004"

  # Configuration globale pour VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # === Serveur K3s ===
  config.vm.define "tde-los-S" do | server |
    server.vm.hostname = "tde-los-S"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provision "shell", path: "scripts/install_server.sh"
  end

  # === Agent K3s ===
  config.vm.define "tde-los-SW" do | worker |
    worker.vm.hostname = "tde-los-SW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    # Ajout d'une dépendance pour forcer l'ordre
    worker.vm.provision "wait-for-server", type: "shell", inline: <<-SHELL
      echo "Waiting for node-token to be created..."
      while [ ! -f /vagrant/confs/node-token ]; do
        sleep 2
      done
      echo "node-token found!"
    SHELL

    worker.vm.provision "shell", path: "scripts/install_agent.sh"
  end

end


